// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/drewbrew": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/studio/login": {
    params: {};
  };
  "/studio": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/drewbrew" | "/blog" | "/blog/:slug" | "/studio/login" | "/studio" | "/*";
  };
  "../src/components/Layout.jsx": {
    id: "../src/components/Layout";
    page: "/" | "/about" | "/contact" | "/drewbrew" | "/blog" | "/blog/:slug" | "/studio/login" | "/studio";
  };
  "../src/pages/Home.jsx": {
    id: "../src/pages/Home";
    page: "/";
  };
  "../src/pages/About.jsx": {
    id: "../src/pages/About";
    page: "/about";
  };
  "../src/pages/Contact.jsx": {
    id: "../src/pages/Contact";
    page: "/contact";
  };
  "../src/pages/DrewBrew.jsx": {
    id: "../src/pages/DrewBrew";
    page: "/drewbrew";
  };
  "../src/pages/BlogIndex.jsx": {
    id: "../src/pages/BlogIndex";
    page: "/blog";
  };
  "../src/pages/BlogPost.jsx": {
    id: "../src/pages/BlogPost";
    page: "/blog/:slug";
  };
  "../src/pages/Login.jsx": {
    id: "../src/pages/Login";
    page: "/studio/login";
  };
  "../src/pages/Admin.jsx": {
    id: "../src/pages/Admin";
    page: "/studio";
  };
  "../src/pages/NotFound.jsx": {
    id: "../src/pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/components/Layout": unknown;
  "../src/pages/Home": unknown;
  "../src/pages/About": unknown;
  "../src/pages/Contact": unknown;
  "../src/pages/DrewBrew": unknown;
  "../src/pages/BlogIndex": unknown;
  "../src/pages/BlogPost": unknown;
  "../src/pages/Login": unknown;
  "../src/pages/Admin": unknown;
  "../src/pages/NotFound": unknown;
};